---
name: Codespell

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  # pull_request trigger disabled so only PR Open API E2E runs on PRs.
  merge_group:

permissions:
  contents: read

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
